using ITCareerPlatform.Models;
using ITCareerPlatform.Services;
using Xunit;

namespace ITCareerPlatform.Tests;

/// <summary>
/// RESET+: Admin đặt lại mật khẩu có thể (a) GÕ mật khẩu tay, hoặc (b) để hệ thống tự sinh
/// mật khẩu mạnh (SuggestStrongPassword để giao diện gợi ý sẵn). Bổ sung cho PasswordResetTests.
/// </summary>
public class ResetPasswordManualTests
{
    private const string OldPassword = "12345678";

    private static (UserService Svc, AuthService Auth) NewServices(TestDb t) =>
        (new UserService(t.Db, new AuditService(t.Db)), new AuthService(t.Db));

    [Fact]
    public void Reset_WithManualPassword_UsesThatExactPassword()
    {
        using var t = new TestDb();
        var admin = t.AddUser("Admin", "admin@itcp.vn", Roles.AdminId);
        var sv = t.AddUser("SV", "sv@itcp.vn", Roles.StudentId);
        var (svc, auth) = NewServices(t);

        var chosen = "MatKhauAdminDat123";
        Assert.True(svc.ResetPassword(sv.Id, admin.Id, out var temp, out var err, manualPassword: chosen), err);

        Assert.Equal(chosen, temp);                              // trả về đúng mật khẩu đã gõ
        Assert.NotNull(auth.Validate("sv@itcp.vn", chosen));     // đăng nhập được bằng nó
        Assert.Null(auth.Validate("sv@itcp.vn", OldPassword));   // mật khẩu cũ hết hiệu lực
        Assert.True(t.NewContext().Users.Find(sv.Id)!.MustChangePassword); // vẫn buộc đổi lại
    }

    [Fact]
    public void Reset_WithTooShortManualPassword_IsRejected()
    {
        using var t = new TestDb();
        var admin = t.AddUser("Admin", "admin@itcp.vn", Roles.AdminId);
        var sv = t.AddUser("SV", "sv@itcp.vn", Roles.StudentId);
        var (svc, auth) = NewServices(t);

        Assert.False(svc.ResetPassword(sv.Id, admin.Id, out _, out var err, manualPassword: "abc"));
        Assert.Contains("tối thiểu", err);
        Assert.NotNull(auth.Validate("sv@itcp.vn", OldPassword));   // không đổi gì cả
    }

    [Fact]
    public void Reset_WithBlankManualPassword_FallsBackToAutoGenerated()
    {
        using var t = new TestDb();
        var admin = t.AddUser("Admin", "admin@itcp.vn", Roles.AdminId);
        var sv = t.AddUser("SV", "sv@itcp.vn", Roles.StudentId);
        var (svc, _) = NewServices(t);

        Assert.True(svc.ResetPassword(sv.Id, admin.Id, out var temp, out _, manualPassword: "   "));
        Assert.True(temp.Length >= 12);   // rơi về mật khẩu mạnh tự sinh
    }

    [Fact]
    public void SuggestStrongPassword_IsStrongAndRandom()
    {
        using var t = new TestDb();
        var (svc, _) = NewServices(t);

        var a = svc.SuggestStrongPassword();
        var b = svc.SuggestStrongPassword();

        Assert.True(a.Length >= 12);
        Assert.Contains(a, char.IsDigit);
        Assert.Contains(a, char.IsLetter);
        Assert.NotEqual(a, b);   // hai lần gợi ý khác nhau (nguồn ngẫu nhiên mật mã học)
    }
}
